### PR TITLE
Fix #88 unhandled permission error and misuse ES6 arrow function

### LINKED ISSUE #88: Unable to install in ubuntu 14.04
I tried installing it in Ubuntu 14.04 but it does not work, please help.
```
$ sudo npm install ngrok -g
npm http GET https://registry.npmjs.org/ngrok
npm http 304 https://registry.npmjs.org/ngrok
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/decompress-zip
npm http GET https://registry.npmjs.org/lock
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/decompress-zip
npm http 304 https://registry.npmjs.org/lock
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/types/node
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-87-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ngrok" "-g"
npm ERR! cwd /home/akshay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/akshay/npm-debug.log
npm ERR! not ok code 0

```

### PR DESCRIPTION
**Pull request by gaoqiankun**

### CODE REVIEW

**Comment by bubenshchykov** [comment]
why not adding on('error') handler to the streams, instead of global uncaught for the process? :)

**Comment by bubenshchykov** [comment]
there are 3 streams missing on('error') handler:
```
var outputStream = fs.createWriteStream(tempFile);
var readStream = fs.createReadStream(tempFile);
fs.createWriteStream(localFile)
```

**Comment by bubenshchykov** [comment]
@gaoqiankun thx for pr, i've pushed this changes here
https://github.com/bubenshchykov/ngrok/commit/e57f84f31a2c4fb16e29906f9d89257bc22f5bb5

**Comment by gaoqiankun** [comment]
Maybe we should just tell people what happened and exit process,  but your code will go to retry function, do you think we should retry when those stream error occur?

**Comment by bubenshchykov** [comment]
Take a look at the latest code, i fixed multiple issues, and also avoided
temporary stream, that were giving permissions error. Yes, whatever happens
now - we report errors clearly, and retry

**Comment by bubenshchykov** [comment]
As for error handling, each stream or pipe should have on('error') handler
to prevent uncaught, and process.exit should be used once in application. I
didn't want to use it, as it could catch someone's else error outside
postinstall.js :)

**Pull request closed without merging**
