### PR TITLE
Add arm and arm64 support for Android

### PR DESCRIPTION
**Pull request by otgo**
I have tested Ngrok on Android (using Termux and arm64 binary) and it works, but I can't install by Termux using this npm package.

### CODE REVIEW

**Comment by otgo** [comment]
I seen you have 'arch' names organized by letter :(
I barely noticed

**Comment by bubenshchykov** [comment]
hi @otgo 
module reads arch from require('os').platform()
node.js detects those arch-s at the moment
```
'aix'
'darwin'
'freebsd'
'linux'
'openbsd'
'sunos'
'win32'
```
how did you get "android" returned?

**Comment by bubenshchykov** [comment]
https://nodejs.org/api/os.html#os_os_platform

**Comment by otgo** [comment]
Using Termux returns that, it is actually the output using Termux (installing NodeJS on Android)
Im going to send you a capture

**Comment by otgo** [comment]
Screenshot_20190728-145704_Termux

**Comment by otgo** [comment]
(Linux ARM X binary works with Android tested, i've been tested)

**Comment by bubenshchykov** [comment]
wow, so node.js returns "android" even though official docs say nothing about it =)
no harm merging this PR, will push to npm in a second

**Comment by otgo** [comment]
Great friend!

**Comment by bubenshchykov** [comment]
merged and pushed to npm
thx man!

**Comment by otgo** [comment]
Tested and it works! Thx 4 u
Screenshot_20190728-150852_Termux

**Comment by otgo** [comment]
I noticed,  with version 2.3.34 doesn't work (stay on reconnecting)

I tested with v.2.2.8 and it works, can you test on Termux?
Maybe v.2.3.x doesnt work perfectly on Android

**Comment by bubenshchykov** [comment]
the binary it uses is the same - binary is downloaded from ngrok.com hosting during postinstal, no matter which module version is that

it looks like you are not using it from inside node.js, can it be easier for you to just install it manually (or as a part of build) from ngork hosting?

**Comment by otgo** [comment]
Must test on different Android versions, maybe v2.3.x bin (ARM) doesn't work as good as on Linux (other arch)

**Pull request merged**
