### PR TITLE
setAuthtoken doesn't use binPath option

### PR DESCRIPTION
**Pull request by april418**
I found a problem that the binPath option does not work.
Please review the code and if it is okay merge it.

### CODE REVIEW

**Comment by bubenshchykov** [comment]
hi, thx for looking into it!
binPath is an optional parameter - should be used for electron only
what was the problem with it?

**Comment by bubenshchykov** [comment]
ah, I see - so binPath was ignored by authToken, right? and your pr fixes that
is it correct?

**Comment by april418** [comment]
Hi, Thank you for checking.

Yes. That's right.

I was creating express web server in Typescript.
The execution path of ngrok.exe in the source using webpack is incorrect.
Therefore, I used the binPath options, I noticed that the execution destination path of ngrok.exe can not be changed in the setAuthtoken.

The status of Travis CI is due to error, not test failure.
An error occurred when the version of Node is 10.
I do not know about this.
When the version of Node is 8, all the tests are working properly.

**Comment by bubenshchykov** [comment]
Thanks, I’ll check that and review the PR

**Comment by bubenshchykov** [comment]
travis is green after re-running :)
thx april418!

**Comment by bubenshchykov** [comment]
published on npm, ngrok@3.1.0

**Pull request merged**
