### PR TITLE
Handle ngrok version 3

### PR DESCRIPTION
**Pull request by philnash**
I think this is all that is needed to handle ngrok 3 (#271). It updates the `authtoken` function to handle making  a different command based on whether the underlying ngrok executable is version 2 or version 3. It also adds an `upgradeConfig` method to upgrade ngrok config so that the new version can read it.

### CODE REVIEW

**Comment by bubenshchykov** [comment]
looks great to me! thanks again <3

**Comment by viralpickaxe** [comment]
Hey guys 👋🏻, do we know when this is going to get a merge? 👀

**Comment by bubenshchykov** [comment]
@philnash it LGTM, do you see any concerns merging it?

**Comment by smithki** [comment]
Really looking forward to seeing this merged!

**Comment by philnash** [comment]
Apologies, I’ve been travelling bunch recently and not able to spend time with this. I’ve no concerns merging, and I can do next week. But if @bubenshchykov wants to and make a release I’m perfectly happy with that too.

**Comment by philnash** [comment]
So, I think the download of ngrok version 3 is a different URL to the download of version 2. This means that this change is not required under version 2, and indeed we can take a step back, update the download URLs and make a major version change in this library to bring in ngrok 3.

**Comment by philnash** [comment]
I think this is ready for an actual review, with an eye on merging and releasing version 5 of this library!

Note, I still haven't used any of the new ngrok features (OAuth, etc) so I don't know how that works yet, or whether this library fully supports using that. That's something to find out though, as we release the new version and find out who wants to use those features.

**Comment by russorat** [comment]
Thanks @philnash ! anything we can do to move this forward?

**Comment by russorat** [comment]
Hi, PM from ngrok here. Really looking to get this PR moving. Let me know if there's anything I can help with.

**Comment by meetkoriya13** [comment]
@philnash any updates on when this is getting merged?

**Review by bubenshchykov — APPROVED** [review]

**Comment by bubenshchykov** [comment]
@philnash, PR looks good, I merged it, super sorry if caused a delay. 

I don't have a laptop to fix a small test failure (one of ngrok error texts changed) and to bump the version on npm. Could you please do it?

**Comment by philnash** [comment]
Hey @bubenshchykov! I just hadn't got around to this too, wasn't necessarily blocked on you.

I will try to find some time this week to fix the failure and push out a beta/rc version. I'd really like to test this out in my VSCode extension to make sure it works ok and to hopefully write up any migration requirements too.

**Pull request merged**
