### PR TITLE
Add TypeScript declaration file

### PR DESCRIPTION
**Pull request by toverux**
Hello @bubenshchykov,

I'm happy to propose you a declaration file for TypeScript.
If you're unfamiliar with TypeScript, that lets API consumers to use dotenv-extended in a type-safe manner.

I could have published the types on DefinitelyTyped, but embedded types are much more practical and are easier to sync when the JavaScript changes.
In fact, bundling types with the original JavaScript library is recommended by the official documentation:

> If you control the npm package you are publishing declarations for, then the first approach is favored. That way, your declarations and JavaScript always travel together.
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> If you are the library author, or can make a pull request to the library, bundle types instead of publishing to DefinitelyTyped.
https://github.com/DefinitelyTyped/DefinitelyTyped

Thanks for your work, and I hope you will merge this (I can help to maintain!).

Edit : I see that the Travis build fails because of some unset authentication environment variables. Did I missed something or is it expected?

### CODE REVIEW

**Comment by bubenshchykov** [comment]
Hi, thanks a lot! :)

Yes, Travis doesn't not expose sensitive env vars to PR branches, so test suite works in master only. Or locally, with your own ngrok authtokens. 

Quick thought - is it all to get a better IntelliSense or other intelligent code completion?

**Comment by toverux** [comment]
> Quick thought - is it all to get a better IntelliSense or other intelligent code completion?

Well, the main goal of TypeScript is to bring a strict type-system to JavaScript. It permits to avoid lots of the basic mistakes we always repeat when working with dynamic languages.
The nice, non-negligible side effect, of course, is that you get a self-documented API and advanced code-completion. It's especially pleasant to work with TypeScript for those reasons (in an IDE like JetBrain's ones or a well-configured text editor): easier refactorings, less mistakes, jump to declaration (eg to read the docs), code-completion, etc. That is, you [trust the compiler](https://slack.engineering/typescript-at-slack-a81307fa288d).

It's obviously easier when you write a library in TypeScript, because at build-time, the declaration files are emitted alongside of the dist JavaScript sources. For JavaScript libraries, we need to write those files by hand, like I did. Good typings are rapidly addictive.

**Comment by bubenshchykov** [comment]
Great explanation, thx! I think it's a job of IDEs to understand code and provide code completion and function jumps for those who wants it. Even Sublime does it quite ok. Other than that, I'm not a fan of strict type systems and TypeScript at the moment. I love the argument about robustness, but I'm trying to achieve the same by reducing complexities.

Since this module is not only for me, I'm more than happy to accept this PR :)
Two questions
- shouldn't @types/node be in devDependencies?
- do people need to modify ngrok.d.ts manually each time interface changes?

**Comment by toverux** [comment]
> I think it's a job of IDEs to understand code and provide code completion and function jumps for those who wants it. Even Sublime does it quite ok.

Of course, WebStorm does a pretty good job at that too. But as JavaScript is an extremely dynamic language, where everythings works by value, at runtime, and due to the diversity of the build/module systems, it's an impossible task to do that correctly. Sublime, without plugins, only find function declarations (or not much more) and will provide token-base completion without any semantic sense.

> I'm not a fan of strict type systems and TypeScript at the moment.

TypeScript stays very close to JavaScript's phylosophy. It's typing system is very flexible and modern, with lots of type inference. It's not like a C# or Java for JavaScript, it's JavaScript with explicit types and type inference.

However, I can totally understand your point of view about transpilers, types and complexity ;)

> shouldn't @types/node be in devDependencies?

Yes, in a normal time. But not for the external @types that are part of your public API. Otherwise the API consumer would have to install it in its own package.

> do people need to modify ngrok.d.ts manually each time interface changes?

Yes, when that file is manually created to type a non-TypeScript lib, like here. But does that interface often change? And event if you add something, a function, an option, etc, and forget to update the .d.ts, this won't break. TS does not have any influence at runtime.

For maintenance, you can still ping me, I'd be happy to help if necessary (but as you can see, the syntax is pretty easy).

> I'm more than happy to accept this PR for TypeScript folks though :)

Yeah, I can assure you that it greatly helps. When working with strict mode, declarations files are not optional and you can't compile until you have it. And even if you're not in strict mode, you won't have to comfort you're used to with typed packages.

If you refuse the PR (which I can understand, nothing forces the mainteners to support everything on Earth), I will put the decl on DefinitelyTyped. But it has a drawback for users: they have to install another @types packages alongside yours, and, when you'll change your API, someone has to notice it, and then notice that the decl is not up to date, and then make a PR on DefinitelyTyped. Not a problem on big libs whith lots of people involved, but here, it could easily desync.

**Comment by bubenshchykov** [comment]
Cool, thx for a good input and article you shared! :)

**Comment by toverux** [comment]
Thanks a lot @bubenshchykov ! :tada: 
I'm now watching the repo and don't hesitate to ask for help.
Will you release a version soon so I can wipe the stub in my project? =)

**Comment by bubenshchykov** [comment]
Sure, will bump in 1h when back home :)

**Pull request merged**
