### PR TITLE
Fetches version from ngrok binary

### PR DESCRIPTION
**Pull request by philnash**
Following ideas from #177 here's my implementation.

I didn't add a `try/catch` in the `getVersion` method because the other methods only seem to kill the process and throw the same error. Since we're doing a one off process there isn't anything to kill so I just let any errors bubble straight up.

Let me know what you think.

### CODE REVIEW

**Comment by bubenshchykov** [comment]
Look good to me! Will publish to npm shortly.

**Comment by philnash** [comment]
Hey @bubenshchykov, is it possible to push this (and perhaps some other of my recent PRs) to npm?

Also, if I can help with maintaining the package, I'd be happy to pitch in.

**Comment by bubenshchykov** [comment]
Hi Phil, thank you for the ping! I’ll push everything by EOD. Will surely
appreciate your help maintaining, so will adjust setting too.

**Comment by bubenshchykov** [comment]
Welcome to ngrok collaborators!

Would be nice to configure some automated or one-click publishing to npm, does Github have a tool for that?

Maybe as a part of Travis build?

Just want to make sure you can publish too.

**Pull request merged**
