### PR TITLE
Set authtoken before starting ngrok

### PR DESCRIPTION
**Pull request by nkzawa**
Otherwise connection fails if we pass authtoken as option with each connect.

Related: https://github.com/rase-/zuul-ngrok/pull/7

### CODE REVIEW

**Comment by bubenshchykov** [comment]
hey! thanks, I'll check while build is red and merge it then

**Comment by nkzawa** [comment]
Please, we are waiting for the fix.

**Comment by bubenshchykov** [comment]
The build was failing because of travis node 0.10.x problems. I think it's time to set the tests baseline to 0.11.x and 0.12.x. Thanks for contribution!

**Comment by nkzawa** [comment]
thanks!

**Comment by nkzawa** [comment]
It seems travis doesn't support node.js on OSX. https://github.com/travis-ci/travis-ci/issues/2311
I don't know why it has succeeded before though.

Btw I think it would be nice to run tests on Node v4 rather than v0.11 which is a development version of v0.12.

**Comment by bubenshchykov** [comment]
can't find v4 among versions supported by travis http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by nkzawa** [comment]
It's actually supported e.g, https://github.com/socketio/engine.io/blob/master/.travis.yml . I think they just don't have the doc yet.

**Comment by bubenshchykov** [comment]
bustards :D thanks man, i'll give it a try )

**Pull request merged**
