### PR TITLE
Make configPath an optional config to connect()

### PR DESCRIPTION
**Pull request by edwmurph**

### CODE REVIEW

**Comment by edwmurph** [comment]
I'm not well versed in this codebase but I've verified experimentally that this PR *almost* works as expected. Specifically there seems to be a problem with my implementation if no configPath param is provided. Have you looked into this at all @bubenshchykov ?

**Comment by bubenshchykov** [comment]
hi, nice change!
two things to fix
- can you make it with double-dash "--config" for consistency, please
- you need to make sure that same "--config" is added here too https://github.com/bubenshchykov/ngrok/blob/master/index.js#L168, otherwise it makes "authtoken" usage buggy

**Comment by bubenshchykov** [comment]
also, please do not delete ngrok/bin stub https://github.com/bubenshchykov/ngrok/pull/77/files#diff-80199e6066759aff2f04012334a04137L1
i've added a note about it here
https://github.com/bubenshchykov/ngrok#contributors

**Comment by edwmurph** [comment]
@bubenshchykov the pipeline is failing because of missing env vars. Should I be injecting them somehow in this PR?

**Comment by edwmurph** [comment]
Also I think I made your requested changes but correct me if I'm wrong.

**Comment by bubenshchykov** [comment]
yes, great PR, thanks a lot! before I had ngrok authtokens for tests public, but people started to use them in their projects ))

**Comment by bubenshchykov** [comment]
Congrs your changes are green in master :)
https://travis-ci.org/bubenshchykov/ngrok/builds/228280232

**Comment by edwmurph** [comment]
Great!

**Pull request merged**
