### PR TITLE
Emit a 'tunnel-disconnect' when a tunnel disconnects

### PR DESCRIPTION
**Pull request by andyburke**

### CODE REVIEW

**Comment by bubenshchykov** [comment]
there is already "disconnect" event for that, see test: 
https://github.com/bubenshchykov/ngrok/blob/master/test/ngrok.eventemitter.spec.js#L28

so if it doesn't work - it's a bug. don't you mind using same "disconnect" event and covering your scenario in ngrok.eventemetter.spec.js ?

**Comment by bubenshchykov** [comment]
Hey, nevermind - I'm working on related fix and will push right "disconnect" event tonight. Will let you know!

**Comment by bubenshchykov** [comment]
please try it now, should be fixed in master

**Comment by andyburke** [comment]
lgtm

**Pull request closed without merging**
